### What is numpy?

NumPy is the fundamental package for scientific computing in Python. It is a Python library that provides a multidimensional array
object, various derived objects (such as masked arrays and matrices), and an assortment of routines for fast operations on arrays,
including mathematical, logical, shape manipulation, sorting, selecting, l/O, discrete Fourier transforms, basic linear algebra, basic
statistical operations, random simulation and much more.

At the core of the NumPy package, is the ndarray object. This encapsulates n-dimensional arrays of homogeneous data types

### Numpy Arrays Vs Python Sequences

-> NumPy arrays have a fixed size at creation, unlike Python lists (which can grow dynamically). Changing the size of an 
   ndarray will create a new array and delete the original

-> The elements in a NumPy array are all required to be of the same data type, and thus will be the same size in memory.

-> NumPy arrays facilitate advanced mathematical and other types of operations on large numbers of data. Typically, such
   operations are executed more efficiently and with less code than is possible using Python's built-in sequences.

-> A growing plethora of scientific and mathematical Python-based packages are using NumPy arrays; though these typically
   support Python- sequence input, they convert such input to NumPy arrays prior to processing, and they often NumPy
   arrays.


### Creating Numpy Array

In [3]:
# np.array

import numpy as np 

a = np.array([1,2,3])
print(type(a))

<class 'numpy.ndarray'>


In [5]:
# 2D and 3D

b = np.array([[1,2,3],[4,5,6]])
c = np.array([[1,2,3],[4,5,6],[7,8,9]])
print(b)
print(c)

[[1 2 3]
 [4 5 6]]
[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [ ]:
# dtype

print(np.array([1,2,3],dtype=float))
print(np.array([1,2,3],dtype=bool))
print(np.array([1,2,3],dtype=complex))

[1. 2. 3.]
[ True  True  True]
[1.+0.j 2.+0.j 3.+0.j]


In [5]:
# np.arange

np.arange(1,11,2)

array([1, 3, 5, 7, 9])

In [ ]:
# with reshape

np.arange(1,11).reshape(5,2)     # (5,2) stands for 5 rows and 2 columns
                                 # 5 *2 = 10 and the number of element in the list should be same
                                 # only then reshape can be use 

array([[ 1,  2],
       [ 3,  4],
       [ 5,  6],
       [ 7,  8],
       [ 9, 10]])

In [11]:
# np.ones and np.zeroes

# They are use in neural network to give weights 

print(np.ones((5,2)))
print(np.zeros((2,3)))

[[1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]]
[[0. 0. 0.]
 [0. 0. 0.]]


In [12]:
# np.random

np.random.random((3,4))

array([[0.60268424, 0.35887662, 0.33696024, 0.47708173],
       [0.32727512, 0.39238973, 0.72653247, 0.16658092],
       [0.52596312, 0.41426953, 0.42095186, 0.97441841]])

In [ ]:
# np.linspace
# linear space
# It generates numbers at a given range with equal distance 


print(np.linspace(-10,10,10) )   #lower range,upper range,No. of items you want in between

print(np.linspace(-10,10,10,dtype=int) )   # This will give int values

[-10.          -7.77777778  -5.55555556  -3.33333333  -1.11111111
   1.11111111   3.33333333   5.55555556   7.77777778  10.        ]
[-10  -8  -6  -4  -2   1   3   5   7  10]


In [ ]:
# np.identity

# It has diagonal items 1 and other 0 
np.identity(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

### Array Attributes

In [ ]:
a1 = np.arange(10)
a2 = np.arange(12,dtype=float).reshape(3,4)
a3 = np.arange(8).reshape(2,2,2) # (how many 2D array ,row ,column)

print(a1)   # It is a 1D array also called vector
print(a2)   # matrix
print(a3)   # tensor

[0 1 2 3 4 5 6 7 8 9]
[[ 0.  1.  2.  3.]
 [ 4.  5.  6.  7.]
 [ 8.  9. 10. 11.]]
[[[0 1]
  [2 3]]

 [[4 5]
  [6 7]]]


In [ ]:
# ndim - It tell the number of dimension of array

print(a1.ndim)
print(a2.ndim)
print(a3.ndim)

1
2
3


In [24]:
# shape - It tells the rows , column in array

a1.shape
a2.shape 
a3.shape


(2, 2, 2)

In [27]:
# size - It tells the number of itmes 

a1.size
a2.size
a3.size

8

In [30]:
# itemsize - How much space every items occupy 

a1.itemsize
a2.itemsize
a3.itemsize

8

In [33]:
# dtype - It tells datatype of items 

a1.dtype
a2.dtype
a3.dtype

dtype('int64')

### Changing Datatype

In [43]:
# astype 

a1.astype(np.int32)


array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9], dtype=int32)

### Array Operations

In [47]:
a1 = np.arange(12).reshape(3,4)
a2 = np.arange(12,24).reshape(3,4)

a1

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [50]:
# scalar operations

# arithmetic

a1 * 2 
a1 + 2 
a1 - 2 
a1 / 2 
a1 % 2 

array([[0, 1, 0, 1],
       [0, 1, 0, 1],
       [0, 1, 0, 1]])

In [ ]:
# relational

In [ ]:
# vector operations
# arithmetic