### np.sort

Return a sorted copy of an array

In [2]:
# code

import numpy as np
a = np.random.randint(1,100,15)
np.sort(a)

array([13, 30, 34, 38, 39, 60, 66, 72, 74, 76, 78, 81, 82, 90, 94],
      dtype=int32)

In [ ]:
b = np.random.randint(1,100,25).reshape(5,5)
np.sort(b)    # It does rowwise sorting
np.sort(b,axis= 0)  # It does columnwise sorting

array([[10, 20, 28,  6, 64],
       [19, 59, 53, 16, 71],
       [47, 65, 72, 53, 74],
       [83, 66, 77, 56, 86],
       [97, 98, 83, 69, 97]], dtype=int32)

### np.append

The numpy.append() appends values along the mentioned axis at the end of the array

In [12]:
np.append(a,200)

array([ 30,  94,  72,  82,  76,  78,  74,  39,  60,  66,  38,  90,  13,
        34,  81, 200])

In [14]:
np.append(b,np.ones((b.shape[0],1)), axis = 1)

array([[83., 66., 83.,  6., 86.,  1.],
       [47., 59., 77., 69., 74.,  1.],
       [19., 65., 53., 56., 64.,  1.],
       [97., 20., 28., 53., 97.,  1.],
       [10., 98., 72., 16., 71.,  1.]])

### np.concatenate

numpy.concatenate() function concatenate a sequence of arrays along an existing axis

In [18]:
c = np.arange(6).reshape(2,3)
d = np.arange(6,12).reshape(2,3)

np.concatenate((c,d),axis = 0)

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [19]:
np.concatenate((c,d),axis = 1)

array([[ 0,  1,  2,  6,  7,  8],
       [ 3,  4,  5,  9, 10, 11]])

### np.unique()

With the help of np.unique() method, we can get the unique values from an array given as parameter in np.unique() method.

In [20]:
e = np.array([1,1,1,1,1,2,2,2,2,2,3,3,3])

np.unique(e)

array([1, 2, 3])

### np.expand_dims

With the help of this, we can get the expanded dimensions of an array 

In [ ]:
a
np.expand_dims(a,axis = 0)     # With this you can change 1D to 2D or 3D to 1D everything viseversa 

(1, 15)

### np.where

the numpy.where() function returns the indices of elements in an input array where the given condition is satisfied

In [25]:
# find all indices with value greater than 50

np.where(a>50)

(array([ 1,  2,  3,  4,  5,  6,  8,  9, 11, 14]),)

In [26]:
# replace all values greater than 50 wiht 0 
# np.where(condition,true,false)

np.where(a>50,0,a)

array([30,  0,  0,  0,  0,  0,  0, 39,  0,  0, 38,  0, 13, 34,  0],
      dtype=int32)

In [27]:
np.where(a%2==0,0,a)

array([ 0,  0,  0,  0,  0,  0,  0, 39,  0,  0,  0,  0, 13,  0, 81],
      dtype=int32)

### np.argmax

The numpy.argmax() function returns indices of the max element of the array in a particular axis

In [29]:
np.argmax(a)

np.int64(1)

In [30]:
np.argmax(b,axis=0)

array([3, 4, 0, 1, 3])

### np.argmin

In [31]:
np.argmin(a)

np.int64(12)

### np.cumsum

numpy.cumsum() function is used when we want to compute the cumulative sum of array elements over a given axis

In [33]:
a

array([30, 94, 72, 82, 76, 78, 74, 39, 60, 66, 38, 90, 13, 34, 81],
      dtype=int32)

In [32]:
np.cumsum(a)

array([ 30, 124, 196, 278, 354, 432, 506, 545, 605, 671, 709, 799, 812,
       846, 927])

In [34]:
np.cumsum(b,axis=0)

array([[ 83,  66,  83,   6,  86],
       [130, 125, 160,  75, 160],
       [149, 190, 213, 131, 224],
       [246, 210, 241, 184, 321],
       [256, 308, 313, 200, 392]])

### np.cumprod

numpy.cumsum() function is used when we want to compute the cumulative product of array elements over a given axis

In [35]:
np.cumprod(a)

array([                  30,                 2820,               203040,
                   16649280,           1265345280,          98696931840,
              7303572956160,      284839345290240,    17090360717414400,
        1127963807349350400,  5969136531856211968,  2266709729482080256,
       -7426261664152059904,  5761520450763685888,  5514554669119766528])

### np.percentile

numpy.percentile() function used to compute the nth percentile of the given data (array elements) along the specified axis

In [ ]:
np.percentile(a,100)  # (a,percentile)

np.float64(94.0)

In [38]:
np.median(a)

np.float64(72.0)

In [39]:
np.mean(a)

np.float64(61.8)

### np.histogram

Numpy has build-in numpy.histogram() function which represents the frequency of data distribution in the graphical form  

In [41]:
np.histogram(a,bins =[0,10,20,30,40,50,60,70,80,90,100] )

(array([0, 1, 0, 4, 0, 0, 2, 4, 2, 2]),
 array([  0,  10,  20,  30,  40,  50,  60,  70,  80,  90, 100]))

### np.conrrcoef

Return Pearson product-moment correlation coefficients 

In [42]:
salary = np.array([200,300,400,500])
experience = np.array([1,2,3,4])

np.corrcoef(salary,experience)

array([[1., 1.],
       [1., 1.]])

### np.isin

With the help of np.isin() method,we can see that one array having values are checked in  different numpy array having different elements with different sizes

In [44]:
items = [10,20,30,40,50,60,70,80,100]

a[np.isin(a,items)]

array([30, 60], dtype=int32)

### np.flip()

The np.flip() function reverse the order of array elements along the specified axis,preserving the shape of the array

In [45]:
np.flip(a)

array([81, 34, 13, 90, 38, 66, 60, 39, 74, 78, 76, 82, 72, 94, 30],
      dtype=int32)

In [46]:
np.flip(b)

array([[71, 16, 72, 98, 10],
       [97, 53, 28, 20, 97],
       [64, 56, 53, 65, 19],
       [74, 69, 77, 59, 47],
       [86,  6, 83, 66, 83]], dtype=int32)

### np.put

The np.put() function replaces specific elements of an array with given values of p_array.Array indexed works on flattened array

In [ ]:
np.put(a,[0,1],[110,530])

# Put 110 at position 0 and 530 at position 1 in array a.

### np.delete

the np.delete() function returns a new array with the deletion of sub-arrays along with the mentioned axis

In [51]:
np.delete(a,0)  # This delete 0 index number 
np.delete(a,[1,2,3])  # This delete 1,2,3 index number 

array([110,  76,  78,  74,  39,  60,  66,  38,  90,  13,  34,  81],
      dtype=int32)

### Set functions

~ np.union1d


~np.intersect1d


~np.setdiff1d


~np.setxor1d


~np.in1d

In [52]:
m = np.array([1,2,3,4,5])
n = np.array([8,9,6,7,5])

np.union1d(m,n)

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [53]:
np.intersect1d(m,n)

array([5])

In [55]:
np.setdiff1d(m,n)
np.setdiff1d(n,m)

array([6, 7, 8, 9])

In [ ]:
np.setxor1d(m,n)  # It will remove all common 

array([1, 2, 3, 4, 6, 7, 8, 9])

In [57]:
np.in1d(m,1)

AttributeError: module 'numpy' has no attribute 'in1d'

### np.clip

np.clip() function is used to clip (limit) the values in an array 

In [58]:
np.clip(a,a_min=25,a_max=75)

array([75, 75, 72, 75, 75, 75, 74, 39, 60, 66, 38, 75, 25, 34, 75],
      dtype=int32)