### What is numpy?

NumPy is the fundamental package for scientific computing in Python. It is a Python library that provides a multidimensional array
object, various derived objects (such as masked arrays and matrices), and an assortment of routines for fast operations on arrays,
including mathematical, logical, shape manipulation, sorting, selecting, l/O, discrete Fourier transforms, basic linear algebra, basic
statistical operations, random simulation and much more.

At the core of the NumPy package, is the ndarray object. This encapsulates n-dimensional arrays of homogeneous data types

### Numpy Arrays Vs Python Sequences

-> NumPy arrays have a fixed size at creation, unlike Python lists (which can grow dynamically). Changing the size of an 
   ndarray will create a new array and delete the original

-> The elements in a NumPy array are all required to be of the same data type, and thus will be the same size in memory.

-> NumPy arrays facilitate advanced mathematical and other types of operations on large numbers of data. Typically, such
   operations are executed more efficiently and with less code than is possible using Python's built-in sequences.

-> A growing plethora of scientific and mathematical Python-based packages are using NumPy arrays; though these typically
   support Python- sequence input, they convert such input to NumPy arrays prior to processing, and they often NumPy
   arrays.


### Creating Numpy Array

In [1]:
# np.array

import numpy as np 

a = np.array([1,2,3])
print(type(a))

<class 'numpy.ndarray'>


In [5]:
# 2D and 3D

b = np.array([[1,2,3],[4,5,6]])
c = np.array([[1,2,3],[4,5,6],[7,8,9]])
print(b)
print(c)

[[1 2 3]
 [4 5 6]]
[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [ ]:
# dtype

print(np.array([1,2,3],dtype=float))
print(np.array([1,2,3],dtype=bool))
print(np.array([1,2,3],dtype=complex))

[1. 2. 3.]
[ True  True  True]
[1.+0.j 2.+0.j 3.+0.j]


In [5]:
# np.arange

np.arange(1,11,2)

array([1, 3, 5, 7, 9])

In [ ]:
# with reshape

np.arange(1,11).reshape(5,2)     # (5,2) stands for 5 rows and 2 columns
                                 # 5 *2 = 10 and the number of element in the list should be same
                                 # only then reshape can be use 

array([[ 1,  2],
       [ 3,  4],
       [ 5,  6],
       [ 7,  8],
       [ 9, 10]])

In [11]:
# np.ones and np.zeroes

# They are use in neural network to give weights 

print(np.ones((5,2)))
print(np.zeros((2,3)))

[[1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]]
[[0. 0. 0.]
 [0. 0. 0.]]


In [12]:
# np.random

np.random.random((3,4))

array([[0.60268424, 0.35887662, 0.33696024, 0.47708173],
       [0.32727512, 0.39238973, 0.72653247, 0.16658092],
       [0.52596312, 0.41426953, 0.42095186, 0.97441841]])

In [ ]:
# np.linspace
# linear space
# It generates numbers at a given range with equal distance 


print(np.linspace(-10,10,10) )   #lower range,upper range,No. of items you want in between

print(np.linspace(-10,10,10,dtype=int) )   # This will give int values

[-10.          -7.77777778  -5.55555556  -3.33333333  -1.11111111
   1.11111111   3.33333333   5.55555556   7.77777778  10.        ]
[-10  -8  -6  -4  -2   1   3   5   7  10]


In [ ]:
# np.identity

# It has diagonal items 1 and other 0 
np.identity(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

### Array Attributes

In [9]:
a1 = np.arange(10)
a2 = np.arange(12,dtype=float).reshape(3,4)
a3 = np.arange(8).reshape(2,2,2) # (how many 2D array ,row ,column)

print(a1)   # It is a 1D array also called vector
print(a2)   # matrix
print(a3)   # tensor

[0 1 2 3 4 5 6 7 8 9]
[[ 0.  1.  2.  3.]
 [ 4.  5.  6.  7.]
 [ 8.  9. 10. 11.]]
[[[0 1]
  [2 3]]

 [[4 5]
  [6 7]]]


In [ ]:
# ndim - It tell the number of dimension of array

print(a1.ndim)
print(a2.ndim)
print(a3.ndim)

1
2
3


In [ ]:
# shape - It tells the rows , column in array

a1.shape
a2.shape 
a3.shape


(2, 2, 2)

In [27]:
# size - It tells the number of itmes 

a1.size
a2.size
a3.size

8

In [30]:
# itemsize - How much space every items occupy 

a1.itemsize
a2.itemsize
a3.itemsize

8

In [33]:
# dtype - It tells datatype of items 

a1.dtype
a2.dtype
a3.dtype

dtype('int64')

### Changing Datatype

In [43]:
# astype 

a1.astype(np.int32)


array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9], dtype=int32)

### Array Operations

In [ ]:
a1 = np.arange(12).reshape(3,4)
a2 = np.arange(12,24).reshape(3,4)

a1

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [ ]:
# scalar operations - Because operation is happing between 1 numpy array and scale

# arithmetic

a1 * 2 
a1 + 2 
a1 - 2 
a1 / 2 
a1 % 2 

array([[0, 1, 0, 1],
       [0, 1, 0, 1],
       [0, 1, 0, 1]])

In [53]:
# relational

a2 > 5
a2 < 5
a2 == 5


array([[False, False, False, False],
       [False, False, False, False],
       [False, False, False, False]])

In [ ]:
# vector operations - Because operation is happing between 2 numpy array 

# This will only work if both array has same shape 

# arithmetic

a2 + a1
a2 ** a1

array([[              1,              13,             196,
                   3375],
       [          65536,         1419857,        34012224,
              893871739],
       [    25600000000,    794280046581,  26559922791424,
        952809757913927]])

### Array Functions

In [59]:
a1 = np.random.random((3,3))
a1 = np.round(a1*100)
a1

array([[89., 49., 60.],
       [64., 78., 49.],
       [83., 49., 27.]])

In [ ]:
# max/min/sum/prod

np.max(a1)
np.min(a1)
np.sum(a1)
np.prod(a1)


# 0 -> col and 1 -> row
np.max(a1,axis=1)   # It gives the maximum row wise  
np.max(a1,axis=0)
# It works on max/min/sum/prod 

array([89., 78., 60.])

In [74]:
# mean/median/std/var

np.mean(a1)
np.median(a1)
np.std(a1)
np.var(a1)


# axis=0 and 1 can also be applied here to all functions 

np.float64(350.5432098765432)

In [75]:
# trigonometric functions

np.sin(a1)

array([[ 0.86006941, -0.95375265, -0.30481062],
       [ 0.92002604,  0.51397846, -0.95375265],
       [ 0.96836446, -0.95375265,  0.95637593]])

In [ ]:
# dot product

a2 = np.arange(12).reshape(3,4)
a3 = np.arange(12,24).reshape(4,3)

np.dot(a2,a3)       # first array col == second array row and new array is form  

array([[114, 120, 126],
       [378, 400, 422],
       [642, 680, 718]])

In [81]:
# log and exponents

np.log(a1)
np.exp(a1)

array([[4.48961282e+38, 1.90734657e+21, 1.14200739e+26],
       [6.23514908e+27, 7.49841700e+33, 1.90734657e+21],
       [1.11286375e+36, 1.90734657e+21, 5.32048241e+11]])

In [86]:
# round/floor/ceil

np.round(np.random.random((2,3)) *100)
np.floor(np.random.random((2,3)) *100)
np.ceil(np.random.random((2,3)) *100)

array([[13., 17., 92.],
       [55., 39., 36.]])

### Indexing 

In [90]:
a1 = np.arange(10)
a2 = np.arange(12).reshape(3,4)
a3 = np.arange(8).reshape(2,2,2)

In [ ]:
a1[-1]   # for 1D array

np.int64(9)

In [ ]:
a2[1,3]   # for 2D array
          # 1 Is for 1st row and 3 is for third column 
          # For item in matrix 

np.int64(7)

In [95]:
a3[1,0,1]  # for 3D array
           # 1 stands for 1st 2D array, 0 stands for 0th row and 1 stands for 1st column   
           # 3D array is make of 2D array and 2D array is make of 1D array 

np.int64(5)

### Slicing

In [98]:
a2

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [ ]:
# 1D

a1[2:5]  

array([2, 3, 4])

In [109]:
# 2D 

a2[0,:]   # 0 stands for first row and : means all column needed 
a2[:,2]   # [row,column] if any section is empyt means include all row or column

a2[1:3,1:3]  
a2[::2,::3]
a2[1::3,0::3]
a2[:2,1:]

array([[1, 2, 3],
       [5, 6, 7]])

In [4]:
a3 = np.arange(27).reshape(3,3,3)
a3

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17]],

       [[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]]])

In [118]:
# 3D array

a3[1,0:,0:]    # 1 stands for which 2D array to choose
a3[0::2]
a3[0::3,1::3,0:]
a3[0::2,0::3,0::2]

array([[[ 0,  2]],

       [[18, 20]]])

### Iterating

In [ ]:
a1

for i in a1:
    print (i)

0
1
2
3
4
5
6
7
8
9


In [ ]:
a2

for i in a2:     # In 2D it prints a row at a time 
    print(i)

[0 1 2 3]
[4 5 6 7]
[ 8  9 10 11]


In [5]:
a3

for i in a3:     # It prints a 2D array at a time 
    print(i)

[[0 1 2]
 [3 4 5]
 [6 7 8]]
[[ 9 10 11]
 [12 13 14]
 [15 16 17]]
[[18 19 20]
 [21 22 23]
 [24 25 26]]


In [ ]:
# to visit each element of array individually

for i in np.nditer(a3):
    print(i)

0
1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19
20
21
22
23
24
25
26


### Reshaping

In [ ]:
# reshape

In [ ]:
# transpose - it changes no. of rows to column and no. column to rows 

np.transpose(a2)
a2.T

array([[ 0.,  4.,  8.],
       [ 1.,  5.,  9.],
       [ 2.,  6., 10.],
       [ 3.,  7., 11.]])

In [13]:
# ravel - it turns any dimension array in 1D

a2.ravel()
a3.ravel()

array([0, 1, 2, 3, 4, 5, 6, 7])

### Stacking

In [ ]:

# horizontal stacking - It is use to add 2 or more numpy array horizontally 


a4 = np.arange(12).reshape(3,4)
a5 = np.arange(12,24).reshape(3,4)
a4
a5


array([[12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [19]:
np.hstack((a4,a5))
np.hstack((a4,a5,a4))

array([[ 0,  1,  2,  3, 12, 13, 14, 15,  0,  1,  2,  3],
       [ 4,  5,  6,  7, 16, 17, 18, 19,  4,  5,  6,  7],
       [ 8,  9, 10, 11, 20, 21, 22, 23,  8,  9, 10, 11]])

In [ ]:
# vertical stacking - It is use to add 2 or more numpy array vertically 

np.vstack((a4,a5))

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

### Splitting

In [ ]:
# horizontal splitting

a4
np.hsplit(a4,2)   # 2 stands for how many parts you want to split

[array([[0, 1],
        [4, 5],
        [8, 9]]),
 array([[ 2,  3],
        [ 6,  7],
        [10, 11]])]

In [27]:
# vertical splitting

np.vsplit(a5,3)

[array([[12, 13, 14, 15]]),
 array([[16, 17, 18, 19]]),
 array([[20, 21, 22, 23]])]